"""Initial schema

Revision ID: b2ac6549064f
Revises: 
Create Date: 2026-06-16 10:28:25.427725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ac6549064f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chatbots_id'), 'chatbots', ['id'], unique=False)
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.drop_index(op.f('idx_resume_uploads_user_id'), table_name='resume_uploads')
    op.create_index(op.f('ix_resume_uploads_id'), 'resume_uploads', ['id'], unique=False)
    op.create_index(op.f('ix_resume_uploads_user_id'), 'resume_uploads', ['user_id'], unique=False)
    op.drop_index(op.f('idx_user_predict_models_user_id'), table_name='user_predict_models')
    op.create_index(op.f('ix_user_predict_models_id'), 'user_predict_models', ['id'], unique=False)
    op.create_index(op.f('ix_user_predict_models_user_id'), 'user_predict_models', ['user_id'], unique=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_username'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_user_predict_models_user_id'), table_name='user_predict_models')
    op.drop_index(op.f('ix_user_predict_models_id'), table_name='user_predict_models')
    op.create_index(op.f('idx_user_predict_models_user_id'), 'user_predict_models', ['user_id'], unique=False)
    op.drop_index(op.f('ix_resume_uploads_user_id'), table_name='resume_uploads')
    op.drop_index(op.f('ix_resume_uploads_id'), table_name='resume_uploads')
    op.create_index(op.f('idx_resume_uploads_user_id'), 'resume_uploads', ['user_id'], unique=False)
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_index(op.f('ix_chatbots_id'), table_name='chatbots')
    # ### end Alembic commands ###
